//-------- userSlice.js ---------->

//-------- Import the createSlice function from Redux Toolkit ---------->
import { createSlice } from "@reduxjs/toolkit";

//-------- Initial state for the user slice ---------->
const initialState = {
  id: "",      //-------- User id ---------->
  name: "",    //-------- User name ---------->
  email: "",   //-------- User email ---------->
  photo: "",   //-------- User photo URL ---------->
};

//-------- Define the user slice using createSlice ---------->
const userSlice = createSlice({
  name: "user",   //-------- Name of the slice ---------->
  initialState,   //-------- Initial state ---------->
  reducers: {
    //-------- Reducer to set user login details ---------->
    setUserLoginDetails: (state, action) => {
      state.id = action.payload.id;
      state.name = action.payload.name;
      state.email = action.payload.email || "";
      state.photo = action.payload.photo;
    },

    //-------- Reducer to set sign-out state ---------->
    setSignOutState: (state) => {
      state.id = "";
      state.name = "";
      state.email = "";
      state.photo = "";
    },
  },
});

//-------- Export the actions generated by the userSlice ---------->
export const { setUserLoginDetails, setSignOutState } = userSlice.actions;

//-------- Selectors to retrieve specific user information from the state ---------->
export const selectUserId = (state) => state.user.id;
export const selectUserName = (state) => state.user.name;
export const selectUserEmail = (state) => state.user.email;
export const selectUserPhoto = (state) => state.user.photo;

//-------- Export the reducer generated by the userSlice ---------->
export default userSlice.reducer;
